#include "shared_vars.hpp"
#include "renderer.hpp"

std::string render_project_app_views_exception_html (const Crails::Renderer*, Crails::SharedVars&)
{
  return
"#include <boost/filesystem.hpp>\n"
"#include <crails/params.hpp>\n"
"#include <algorithm>\n"
"\n"
"using namespace Crails;\n"
"using namespace std;\n"
"\n"
"string  @exception_name;\n"
"string  @exception_what;\n"
"Params& @params;\n"
"// END LINKING\n"
"<% string     backtrace         = params[\"backtrace\"].defaults_to<string>(\"No backtrace available\") -%>\n"
"<% bool       has_controller    = params[\"controller-data\"].exists() -%>\n"
"<% string     controller_name   = params[\"controller-data\"][\"name\"].defaults_to<string>(\"\") -%>\n"
"<% string     controller_method = params[\"controller-data\"][\"action\"].defaults_to<string>(\"\") -%>\n"
"<% if (params[\"backtrace\"].exists()) do -%>\n"
"  <% params[\"backtrace\"].destroy() -%>\n"
"<% end -%>\n"
"<% if (has_controller) do -%>\n"
"  <% params[\"controller-data\"].destroy() -%>\n"
"<% end -%>\n"
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"utf-8\" />\n"
"  <title>Crails Server: Exception caught</title>\n"
"  <style>\n"
"    body { background-color: #fff; color: #333; }\n"
"\n"
"    body, p, ol, ul, td {\n"
"      font-family: helvetica, verdana, arial, sans-serif;\n"
"      font-size:   13px;\n"
"      line-height: 18px;\n"
"    }\n"
"\n"
"    pre {\n"
"      background-color: #eee;\n"
"      padding: 5px;\n"
"      font-size: 12px;\n"
"      overflow: auto;\n"
"      width: 100%;\n"
"    }\n"
"\n"
"    a { color: #000; }\n"
"    a:visited { color: #666; }\n"
"    a:hover { color: #fff; background-color:#000; }\n"
"\n"
"    .crails-logo {\n"
"      float: right;\n"
"      position: relative;\n"
"      background-color: #ff0000;\n"
"      text-align: center;\n"
"      color: white;\n"
"      font-weight: bold;\n"
"      font-size: 2em;\n"
"      width: 80px;\n"
"      margin: 0 auto;\n"
"      padding: 5px 0 20px;\n"
"      line-height: 0.8em;\n"
"      border-top: 10px #f10000 solid;\n"
"    }\n"
"\n"
"    .crails-logo-layer {\n"
"      position: absolute;\n"
"      background-color: #d10000;\n"
"      top: 0;\n"
"      bottom: 0;\n"
"      left: 0;\n"
"      width: 50%;\n"
"      opacity: 0.3;\n"
"    }\n"
"\n"
"    .crails-logo, .crails-logo-layer { border-bottom-left-radius: 60px; }\n"
"    .crails-logo { border-bottom-right-radius: 60px; }\n"
"  </style>\n"
"</head>\n"
"<body>\n"
"\n"
"<div class=\"crails-logo\">\n"
"  <div class=\"crails-logo-layer\"></div>\n"
"  C<br/>\n"
"  +<br/>\n"
"  +<br/>\n"
"</div>\n"
"\n"
"<% if (has_controller == true) do -%>\n"
"  <h1>Exception catched in <%= controller_name %>::<%= controller_method %></h1>\n"
"<% end else do -%>\n"
"  <h1>Exception catched</h1>\n"
"<% end -%>\n"
"<pre style=\"width:calc(100% - 100px)\"><%= exception_what %></pre>\n"
"\n"
"<p><code>Crails directory: <%= boost::filesystem::current_path().string() %></code></p>\n"
"\n"
"<div id=\"traces\">\n"
"    <div id=\"trace\" style=\"display: block;\">\n"
"      <pre><code><%= html_escape(backtrace) %></code></pre>\n"
"    </div>\n"
"</div>\n"
"\n"
"<h2 id=\"request\" style=\"margin-top: 30px\">Request</h2>\n"
"<p><b>Parameters</b>:\n"
"<pre>\n"
"<% if (params.as_data().count() == 0) do -%>\n"
"  This request didn't contain any parameters.\n"
"<% end else do -%>\n"
"  <%= html_escape(params.to_json()) %>\n"
"<% end -%>\n"
"</pre></p>\n"
"\n"
"<p><a href=\"#\" onclick=\"document.getElementById('session_dump').style.display='block'; return false;\">Show session dump</a></p>\n"
"<div id=\"session_dump\" style=\"display:none\">\n"
"  <pre>\n"
"    <%= html_escape(params.get_session().to_json()) %>\n"
"  </pre>\n"
"</div>\n"
"\n"
"</body>\n"
"</html>";
}
