include ../libcrails/
include ../libcrails-http-client/
intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import libs += libcrails%lib{crails}

lib{crails-sentry}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root" "-I$src_root/libcrails" "-I$src_root/libcrails-http-client"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

# Export options.
#
lib{crails-sentry}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{crails-sentry}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails-sentry}: cxx.export.poptions += -DLIBCRAILS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{crails-sentry}: bin.lib.version = "-$version.project_id"
else
  lib{crails-sentry}: bin.lib.version = "-$version.major.$version.minor"

# Install into the crails/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/crails/
  install.subdirs = true
}
