#!/usr/bin/env ruby

source = nil
source = ENV['CRAILS_SHARED_DIR'] unless ENV['CRAILS_SHARED_DIR'].nil?

if source.nil?
  (ENV['XDG_DATA_DIRS'].split ':').each do |dir|
    full_path = "#{dir}/crails"
    if File.directory? full_path
      source = full_path
      break
    end
  end
end

if source.nil?
  puts "Missing crails shared directory. Please check your installation, or manually set the environemnt variable CRAILS_SHARED_DIR."
  exit 1
else
  ENV['CRAILS_SHARED_DIR'] = source
end

command      = ARGV[0]
command_args = ARGV[1..-1].join ' ' rescue ''

if command.nil?
  puts 'Available commands:'
  Dir["#{ENV['CRAILS_SHARED_DIR']}/scripts/*.rb"].each do |cmd|
    cmd_name = cmd.scan(/([^\/]+)[.]rb$/).flatten.first
    puts " - #{cmd_name}"
  end
  exit 0
end

unless command == 'new'
  require 'fileutils'

  until File.exists? 'CMakeLists.txt'
    FileUtils.cd '..'
    if Dir.pwd == '/'
      puts 'You\'re not in a Crails application'
      exit -2
    end
  end
end

##
## Run the command with the proper bundling environment
##
commands_without_bundler = ['new']

def run_command cmd
  system cmd
  $?.exitstatus
end

def find_bundler
  bundler_gemspec = Gem::Specification::find_all_by_name('bundler')
  system_bundler  = `which bundle 2> /dev/null`
  if bundler_gemspec.any?
    bundler_gem = bundler_gemspec.first
    "#{bundler_gem.bin_dir}/#{bundler_gem.executables.first}"
  elsif system_bundler != ""
    system_bundler.split("\n").first
  else
    nil
  end
end

def run_using_bundler cmd
  bundler_bin = find_bundler

  if bundler_bin.nil?
    puts "/!\\ Bundler gem not found. Please install it with `gem install bundler`."
    exit 2
  end

  puts "[crails] Using ruby bundler #{bundler_bin}"

  bundle_cmd = "#{bundler_bin} install"
  bundle_cmd += " --path #{ENV['CRAILS_RUBY_BUNDLE_PATH']}" unless ENV['CRAILS_RUBY_BUNDLE_PATH'].nil?
  cmd = "#{bundler_bin} exec #{cmd}"

  puts `echo "+ bundle check" && #{bundler_bin} check`
  cmd = "#{bundle_cmd} && #{cmd}" unless $?.success?
  run_command cmd
end

cmd = "ruby #{source}/scripts/#{command}.rb #{command_args}"
if commands_without_bundler.include? command
  exit run_command cmd
else
  exit run_using_bundler cmd
end
