#!/usr/bin/env ruby

source = nil
source = ENV['CRAILS_SHARED_DIR'] unless ENV['CRAILS_SHARED_DIR'].nil?

if source.nil?
  (ENV['XDG_DATA_DIRS'].split ':').each do |dir|
    full_path = "#{dir}/crails"
    if File.directory? full_path
      source = full_path
      break
    end
  end
end

if source.nil?
  puts "Missing crails shared directory. Please check your installation, or manually set the environemnt variable CRAILS_SHARED_DIR."
  exit 1
else
  ENV['CRAILS_SHARED_DIR'] = source
end

command      = ARGV[0]
command_args = ARGV[1..-1].join ' ' rescue ''

if command.nil?
  puts 'Available commands:'
  Dir["#{ENV['CRAILS_SHARED_DIR']}/scripts/*.rb"].each do |cmd|
    cmd_name = cmd.scan(/([^\/]+)[.]rb$/).flatten.first
    puts " - #{cmd_name}"
  end
  exit 0
end

unless command == 'new'
  require 'fileutils'

  until (File.exists? 'CMakeLists.txt' and File.exists? 'app' and File.exists? 'public')
    FileUtils.cd '..'
    if Dir.pwd == '/'
      puts 'You\'re not in a Crails application'
      exit -2
    end
  end
end

system "ruby #{source}/scripts/#{command}.rb #{command_args}"
exit $?.exitstatus
